// Generated by tools/blender/emit-scene.mjs from a Blender bake. Do not edit by hand:
// re-bake and run the emitter, so the numbers and the files never disagree.

import type { Pose, ServiceKey, Vec3 } from './types';

export type PoseKey = 'junction' | 'hub' | ServiceKey;

/** One texture at 1x and 2x, as site-root paths. The runtime picks by device pixel ratio. */
export type Picture = { x1: string; x2: string };

/** One way of the K, in three.js coordinates: the angle it leaves the hub at and how far its node stands. */
export type Lane = {
  key: ServiceKey;
  angle: number;
  dist: number;
  node: Vec3;
  back: number;
  aimY: number;
};

export type WayAsset = {
  model: string;
  lightmap: Picture;
  /** Multiplies the 0..1 lightmap back into the bake's own light (lightMapIntensity). */
  lightScale: number;
  anchor: Vec3;
  bounds: { min: Vec3; max: Vec3 };
};

export const SCENE_ORDER: readonly ServiceKey[] = ['website', 'app', 'capacity', 'care'];

/** The letter itself: what crossroads.py drew the floor from, so the runtime lays chips and lights on the same graph. */
export const LAYOUT: {
  rotate: number;
  strokeWidth: number;
  hub: number;
  node: number;
  floorSize: number;
  fade: readonly [number, number];
  lanes: readonly Lane[];
} = {
  rotate: 0.3,
  strokeWidth: 2.1,
  hub: 2.7,
  node: 1.9,
  floorSize: 100,
  fade: [34, 48],
  lanes: [
    {
      key: 'website',
      angle: 0.3,
      dist: 18,
      node: [-5.319, 0, -17.196],
      back: 9.1,
      aimY: 2.33,
    },
    {
      key: 'app',
      angle: -0.512419,
      dist: 26.2,
      node: [12.846, 0, -22.835],
      back: 11.4,
      aimY: 2.6,
    },
    {
      key: 'capacity',
      angle: -2.029174,
      dist: 26.2,
      node: [23.495, 0, 11.593],
      back: 13.2,
      aimY: 0.98,
    },
    {
      key: 'care',
      angle: 3.441593,
      dist: 18,
      node: [5.319, 0, 17.196],
      back: 11.2,
      aimY: 2.78,
    },
  ],
};

export const POSES: Record<PoseKey, Pose> = {
  junction: {
    pos: [14, 32, 30],
    look: [6, 0, 0],
    fitH: 32.8,
    fitV: 15.2,
    fstop: 11,
  },
  hub: {
    pos: [0, 6, 0],
    look: [-5.319, 2.33, -17.196],
    fitH: 24,
    fitV: 18,
    fstop: 8,
  },
  website: {
    pos: [-2.63, 2.4, -8.502],
    look: [-5.319, 2.33, -17.196],
    fitH: 24,
    fitV: 18,
    fstop: 0.8,
  },
  app: {
    pos: [7.256, 2.4, -12.899],
    look: [12.846, 2.6, -22.835],
    fitH: 24,
    fitV: 18,
    fstop: 0.8,
  },
  capacity: {
    pos: [11.658, 2.4, 5.752],
    look: [23.495, 0.98, 11.593],
    fitH: 24,
    fitV: 18,
    fstop: 0.8,
  },
  care: {
    pos: [2.01, 2.4, 6.496],
    look: [5.319, 2.78, 17.196],
    fitH: 24,
    fitV: 18,
    fstop: 0.8,
  },
};

export const WAYS: Record<ServiceKey, WayAsset> = {
  website: {
    model: '/crossroads/scene/website.glb',
    lightmap: {
      x1: '/crossroads/scene/lightmap-website.webp',
      x2: '/crossroads/scene/lightmap-website@2x.webp',
    },
    lightScale: 10.4949,
    anchor: [-5.319, 5.2, -17.196],
    bounds: {
      min: [-7.931, -0.01, -18.099],
      max: [-2.707, 4.65, -16.293],
    },
  },
  app: {
    model: '/crossroads/scene/app.glb',
    lightmap: {
      x1: '/crossroads/scene/lightmap-app.webp',
      x2: '/crossroads/scene/lightmap-app@2x.webp',
    },
    lightScale: 7.8401,
    anchor: [12.209, 5.75, -22.312],
    bounds: {
      min: [8.904, -0.01, -24.597],
      max: [15.514, 5.2, -20.027],
    },
  },
  capacity: {
    model: '/crossroads/scene/capacity.glb',
    lightmap: {
      x1: '/crossroads/scene/lightmap-capacity.webp',
      x2: '/crossroads/scene/lightmap-capacity@2x.webp',
    },
    lightScale: 7.1091,
    anchor: [24.125, 2.395, 11.981],
    bounds: {
      min: [21.118, 0, 7.996],
      max: [27.132, 1.845, 15.966],
    },
  },
  care: {
    model: '/crossroads/scene/care.glb',
    lightmap: {
      x1: '/crossroads/scene/lightmap-care.webp',
      x2: '/crossroads/scene/lightmap-care@2x.webp',
    },
    lightScale: 11.5962,
    anchor: [5.289, 6.096, 17.224],
    bounds: {
      min: [3.262, 0, 15.76],
      max: [7.316, 5.546, 18.687],
    },
  },
};

export const FLOOR: { texture: Picture; scale: number } = {
  texture: {
    x1: '/crossroads/scene/floor.webp',
    x2: '/crossroads/scene/floor@2x.webp',
  },
  scale: 1,
};

/** Bytes of every 1x file above together: what a visitor at 1x fetches. */
export const BYTES_1X = 561166;
