// Generated by tools/blender/emit-stills.mjs from a Blender render. Do not edit by hand:
// re-render and run the emitter, so the anchors and the pictures never disagree.

import type { ServiceKey } from './types';

export type StillKey = 'junction' | ServiceKey;

/**
 * Where a label stands, in still pixels at 1x, x from the left and y from the
 * top. `on` is whether the label is shown on that still: all four at the
 * junction, only its own way in a close-up.
 */
export type Anchor = { x: number; y: number; on: boolean };

export type Still = { src: string; src2x: string; marks: Record<ServiceKey, Anchor> };

/** The still is the free region beside the copy panel at 1440x900, in CSS pixels. */
export const STILL = { width: 808, height: 998 } as const;

export const STILL_ORDER: readonly StillKey[] = ['junction', 'website', 'app', 'capacity', 'care'];

export const STILLS: Record<StillKey, Still> = {
  junction: {
    src: '/crossroads/junction.webp',
    src2x: '/crossroads/junction@2x.webp',
    marks: {
      website: {
        x: 116,
        y: 409,
        on: true,
      },
      app: {
        x: 307,
        y: 398,
        on: true,
      },
      capacity: {
        x: 501,
        y: 466,
        on: true,
      },
      care: {
        x: 694,
        y: 387,
        on: true,
      },
    },
  },
  website: {
    src: '/crossroads/website.webp',
    src2x: '/crossroads/website@2x.webp',
    marks: {
      website: {
        x: 404,
        y: 212,
        on: true,
      },
      app: {
        x: 1555,
        y: -1,
        on: false,
      },
      capacity: {
        x: 81782,
        y: 519,
        on: false,
      },
      care: {
        x: -1416,
        y: 888,
        on: false,
      },
    },
  },
  app: {
    src: '/crossroads/app.webp',
    src2x: '/crossroads/app@2x.webp',
    marks: {
      website: {
        x: -429,
        y: 239,
        on: false,
      },
      app: {
        x: 385,
        y: 227,
        on: true,
      },
      capacity: {
        x: 1340,
        y: 515,
        on: false,
      },
      care: {
        x: 5996,
        y: -862,
        on: false,
      },
    },
  },
  capacity: {
    src: '/crossroads/capacity.webp',
    src2x: '/crossroads/capacity@2x.webp',
    marks: {
      website: {
        x: -3094,
        y: -256,
        on: false,
      },
      app: {
        x: -447,
        y: 73,
        on: false,
      },
      capacity: {
        x: 412,
        y: 402,
        on: true,
      },
      care: {
        x: 1139,
        y: 79,
        on: false,
      },
    },
  },
  care: {
    src: '/crossroads/care.webp',
    src2x: '/crossroads/care@2x.webp',
    marks: {
      website: {
        x: 2892,
        y: 940,
        on: false,
      },
      app: {
        x: -7160,
        y: -1241,
        on: false,
      },
      capacity: {
        x: -426,
        y: 530,
        on: false,
      },
      care: {
        x: 408,
        y: 233,
        on: true,
      },
    },
  },
};
