// Generated by tools/blender/emit-stills.mjs from a Blender render. Do not edit by hand:
// re-render and run the emitter, so the anchors and the pictures never disagree.

import type { ServiceKey } from './types';

export type StillKey = 'junction' | ServiceKey;

/**
 * Where a label stands, in still pixels at 1x, x from the left and y from the
 * top. `on` is whether the label is shown on that still: all four at the
 * junction, only its own way in a close-up.
 */
export type Anchor = { x: number; y: number; on: boolean };

export type Still = { src: string; src2x: string; marks: Record<ServiceKey, Anchor> };

/** The still is the free region beside the copy panel at 1440x900, in CSS pixels. */
export const STILL = { width: 808, height: 998 } as const;

export const STILL_ORDER: readonly StillKey[] = ['junction', 'website', 'app', 'capacity', 'care'];

export const STILLS: Record<StillKey, Still> = {
  junction: {
    src: '/crossroads/junction.webp',
    src2x: '/crossroads/junction@2x.webp',
    marks: {
      website: {
        x: 329,
        y: 296,
        on: true,
      },
      app: {
        x: 539,
        y: 288,
        on: true,
      },
      capacity: {
        x: 691,
        y: 698,
        on: true,
      },
      care: {
        x: 292,
        y: 664,
        on: true,
      },
    },
  },
  website: {
    src: '/crossroads/website.webp',
    src2x: '/crossroads/website@2x.webp',
    marks: {
      website: {
        x: 404,
        y: 212,
        on: true,
      },
      app: {
        x: 2291,
        y: 146,
        on: false,
      },
      capacity: {
        x: -240,
        y: 492,
        on: false,
      },
      care: {
        x: 405,
        y: 616,
        on: false,
      },
    },
  },
  app: {
    src: '/crossroads/app.webp',
    src2x: '/crossroads/app@2x.webp',
    marks: {
      website: {
        x: 5405,
        y: 1587,
        on: false,
      },
      app: {
        x: 379,
        y: 231,
        on: true,
      },
      capacity: {
        x: -1416,
        y: 515,
        on: false,
      },
      care: {
        x: -32,
        y: 638,
        on: false,
      },
    },
  },
  capacity: {
    src: '/crossroads/capacity.webp',
    src2x: '/crossroads/capacity@2x.webp',
    marks: {
      website: {
        x: 868,
        y: 501,
        on: false,
      },
      app: {
        x: 2292,
        y: 652,
        on: false,
      },
      capacity: {
        x: 409,
        y: 402,
        on: true,
      },
      care: {
        x: -11174,
        y: 3686,
        on: false,
      },
    },
  },
  care: {
    src: '/crossroads/care.webp',
    src2x: '/crossroads/care@2x.webp',
    marks: {
      website: {
        x: 404,
        y: 633,
        on: false,
      },
      app: {
        x: 1084,
        y: 655,
        on: false,
      },
      capacity: {
        x: -1100,
        y: 530,
        on: false,
      },
      care: {
        x: 407,
        y: 234,
        on: true,
      },
    },
  },
};
