/**
 * From a Blender render to what the site ships.
 *
 *   node tools/blender/emit-stills.mjs --renders <dir> --poster <dir>
 *
 * `<renders>` holds the five free-frame stills at 2x and their anchors.json,
 * `<poster>` the wide junction render (junction.png, opaque). Out of them:
 *
 *   public/crossroads/<shot>@2x.webp and <shot>.webp   the stills, with alpha
 *   public/crossroads.webp, public/crossroads-phone.webp the poster's two crops
 *   src/components/crossroads/stills.ts                  the generated module
 *
 * The module is the only place the page learns the stills' size, files and
 * label anchors, and this script is the only thing that writes it.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(HERE, '..', '..');
const argv = process.argv.slice(2);
const arg = (name) => {
  const i = argv.indexOf(name);
  if (i < 0) throw new Error(`emit-stills: ${name} is required`);
  return argv[i + 1];
};
const RENDERS = path.resolve(arg('--renders'));
const POSTER = path.resolve(arg('--poster'));

const ORDER = ['junction', 'website', 'app', 'capacity', 'care'];
const WAYS = ['website', 'app', 'capacity', 'care'];
const OUT = path.join(WEB, 'public', 'crossroads');
mkdirSync(OUT, { recursive: true });

const anchors = JSON.parse(readFileSync(path.join(RENDERS, 'anchors.json'), 'utf8'));
const first = anchors[ORDER[0]];
if (!first || first.frame !== 'free')
  throw new Error('emit-stills: the renders are not free-frame stills');
const { width, height } = first;

const kb = (n) => `${(n / 1024).toFixed(1)} kB`;
let total = 0;

const stills = {};
for (const shot of ORDER) {
  const meta = anchors[shot];
  if (!meta) throw new Error(`emit-stills: no render for ${shot}`);
  const png = path.join(RENDERS, `${shot}.png`);
  if (!existsSync(png)) throw new Error(`emit-stills: ${png} is missing`);

  const two = await sharp(png)
    .webp({ quality: 84, alphaQuality: 90 })
    .toFile(path.join(OUT, `${shot}@2x.webp`));
  const one = await sharp(png)
    .resize(width, height, { kernel: 'lanczos3' })
    .webp({ quality: 84, alphaQuality: 90 })
    .toFile(path.join(OUT, `${shot}.webp`));
  total += two.size + one.size;
  console.log(
    `${shot}: ${one.width}x${one.height} ${kb(one.size)}, 2x ${two.width}x${two.height} ${kb(two.size)}`,
  );

  const marks = {};
  for (const way of WAYS) {
    const [x, y] = meta.marks[way];
    marks[way] = { x, y, on: shot === 'junction' || shot === way };
  }
  stills[shot] = { src: `/crossroads/${shot}.webp`, src2x: `/crossroads/${shot}@2x.webp`, marks };
}
console.log(`stills: ${kb(total)} in total`);

// The poster: the strip is the band the four objects and their floor occupy,
// the upright crop is the left half of the fan, where the landing page and
// the dashboard stand. Both are fractions of the wide render.
const poster = path.join(POSTER, 'junction.png');
if (!existsSync(poster)) throw new Error(`emit-stills: ${poster} is missing`);
const pm = await sharp(poster).metadata();
const strip = await sharp(poster)
  .extract({
    left: 0,
    top: Math.round(pm.height * 0.2),
    width: pm.width,
    height: Math.round(pm.height * 0.516),
  })
  .webp({ quality: 80 })
  .toFile(path.join(WEB, 'public', 'crossroads.webp'));
console.log(`poster strip: ${strip.width}x${strip.height} ${kb(strip.size)}`);
const phone = await sharp(poster)
  .extract({
    left: Math.round(pm.width * 0.05),
    top: Math.round(pm.height * 0.13),
    width: Math.round(pm.width * 0.55),
    height: Math.round(pm.height * 0.657),
  })
  .webp({ quality: 80 })
  .toFile(path.join(WEB, 'public', 'crossroads-phone.webp'));
console.log(`poster phone: ${phone.width}x${phone.height} ${kb(phone.size)}`);

const lines = [
  '// Generated by tools/blender/emit-stills.mjs from a Blender render. Do not edit by hand:',
  '// re-render and run the emitter, so the anchors and the pictures never disagree.',
  '',
  "import type { ServiceKey } from './types';",
  '',
  "export type StillKey = 'junction' | ServiceKey;",
  '',
  '/**',
  ' * Where a label stands, in still pixels at 1x, x from the left and y from the',
  ' * top. `on` is whether the label is shown on that still: all four at the',
  ' * junction, only its own way in a close-up.',
  ' */',
  'export type Anchor = { x: number; y: number; on: boolean };',
  '',
  'export type Still = { src: string; src2x: string; marks: Record<ServiceKey, Anchor> };',
  '',
  '/** The still is the free region beside the copy panel at 1440x900, in CSS pixels. */',
  `export const STILL = { width: ${width}, height: ${height} } as const;`,
  '',
  `export const STILL_ORDER: readonly StillKey[] = ${JSON.stringify(ORDER)};`,
  '',
  `export const STILLS: Record<StillKey, Still> = ${JSON.stringify(stills, null, 2)};`,
  '',
];
const module = path.join(WEB, 'src', 'components', 'crossroads', 'stills.ts');
writeFileSync(module, lines.join('\n'));
execFileSync('npx', ['prettier', '--write', module], { cwd: WEB, stdio: 'ignore' });
console.log(`wrote ${path.relative(WEB, module)}`);
