"""Build a brand-system board that reuses the site's own compiled CSS and fonts,
so every specimen is rendered in the real typefaces and the real token values."""

import re
from pathlib import Path

# Resolved from this file, not hard-coded, so the repo can move or be renamed.
ROOT = Path(__file__).resolve().parents[2]
WEB = ROOT / "web"
LOGO = ROOT / "brand" / "logo"
OUT = WEB / "out"

html_src = (OUT / "de/index.html").read_text()
cls = re.search(r'<html lang="de" class="([^"]+)"', html_src).group(1)
css = re.search(r'href="(/_next/static/css/[^"]+)"', html_src).group(1)


def svg(name, width=None, extra=""):
    s = (LOGO / name).read_text()
    s = re.sub(r'\swidth="[^"]*"', "", s, count=1)
    s = re.sub(r'\sheight="[^"]*"', "", s, count=1)
    style = f'style="width:{width};height:auto;{extra}"' if width else ""
    return s.replace("<svg ", f"<svg {style} ", 1)


VIRIDIAN = [
    ("50", "#F0F9F4", 1.0, 15.37),
    ("100", "#DEF3E5", 1.09, 14.19),
    ("200", "#BFE5CC", 1.28, 12.02),
    ("300", "#9ED3AF", 1.59, 9.74),
    ("400", "#7DBD90", 2.06, 7.51),
    ("500", "#5EA472", 2.79, 5.52),
    ("600", "#488859", 3.97, 3.88),
    ("700", "#396C43", 5.78, 2.67),
    ("800", "#2B5131", 8.45, 1.83),
    ("900", "#1D3720", 12.13, 1.27),
    ("950", "#112413", 15.28, 1.01),
]
STONE = [
    ("50", "#F5F8F6", 1.0, 15.43),
    ("100", "#EAEEEB", 1.1, 14.09),
    ("200", "#D7DBD8", 1.31, 11.8),
    ("300", "#C1C5C2", 1.63, 9.45),
    ("400", "#A8ADA9", 2.13, 7.24),
    ("500", "#8E938F", 2.92, 5.28),
    ("600", "#757975", 4.14, 3.73),
    ("700", "#5C605C", 5.98, 2.58),
    ("800", "#444844", 8.7, 1.77),
    ("900", "#2D322D", 12.23, 1.26),
    ("950", "#1C201C", 15.43, 1.0),
]


def swatches(scale, star=None):
    out = []
    for step, hexv, onp, oni in scale:
        mark = " ★" if step == star else ""
        out.append(
            f'<div style="flex:1;min-width:0">'
            f'<div style="height:74px;background:{hexv};border-radius:6px;'
            f'border:1px solid rgba(12,26,21,.08)"></div>'
            f'<div style="margin-top:7px;font:500 10px/1.35 var(--font-mono);'
            f'color:var(--kc-text)">{step}{mark}</div>'
            f'<div style="font:400 10px/1.35 var(--font-mono);color:var(--kc-textMuted)">'
            f'{hexv}</div>'
            f'<div style="font:400 9px/1.4 var(--font-mono);color:var(--kc-textMuted);'
            f'margin-top:3px">{onp:.2f} / {oni:.2f}</div>'
            f"</div>"
        )
    return "".join(out)


def eyebrow(t):
    return (
        f'<p style="font:500 11px/1.2 var(--font-mono);letter-spacing:.08em;'
        f'text-transform:uppercase;color:var(--kc-brandText);margin:0 0 10px">{t}</p>'
    )


def h2(t):
    return (
        f'<h2 style="font:700 30px/1.1 var(--font-display);letter-spacing:-.02em;'
        f'margin:0 0 6px;color:var(--kc-text)">{t}</h2>'
    )


def note(t):
    return (
        f'<p style="font:400 13px/1.6 var(--font-body);color:var(--kc-textMuted);'
        f'margin:0 0 26px;max-width:78ch">{t}</p>'
    )


def panel(inner, dark=False, pad=26):
    bg = "var(--kc-stone-900)" if dark else "var(--kc-surface)"
    return (
        f'<div style="background:{bg};border:1px solid var(--kc-border);'
        f'border-radius:10px;padding:{pad}px">{inner}</div>'
    )


def cap(t, dark=False):
    c = "var(--kc-stone-400)" if dark else "var(--kc-textMuted)"
    return (
        f'<p style="font:400 10px/1.3 var(--font-mono);text-transform:uppercase;'
        f'letter-spacing:.06em;color:{c};margin:14px 0 0">{t}</p>'
    )


SHEETS = []

# ---------------------------------------------------------------- sheet 1
SHEETS.append(f"""
<div style="display:flex;align-items:flex-start;justify-content:space-between;gap:40px">
  <div>
    {eyebrow('Brand system · 01')}
    {h2('The logo')}
    {note('Seventeen files, all generated by build_logos.py. The wordmark is outlined paths, never &lt;text&gt; — a &lt;text&gt; logo silently falls back to Arial wherever Space Grotesk is not installed.')}
  </div>
  <div style="flex-shrink:0">{svg('klucode-logo-horizontal.svg', '250px')}</div>
</div>

<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px">
  {panel(svg('klucode-logo-horizontal.svg','300px') + cap('Primary lockup — the default'))}
  {panel(svg('klucode-logo-horizontal-on-dark.svg','300px') + cap('On ink', True), dark=True)}
</div>

<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:18px;margin-top:18px">
  {panel(svg('klucode-logo-stacked.svg','150px') + cap('Stacked — square spaces'))}
  {panel(svg('klucode-mark.svg','150px') + cap('Mark alone — min 32px'))}
  {panel(svg('klucode-wordmark.svg','200px') + cap('Wordmark — very wide spaces'))}
</div>

<div style="display:grid;grid-template-columns:2fr 1fr;gap:18px;margin-top:18px">
  {panel(
    '<div style="display:flex;align-items:flex-end;gap:26px">'
    + "".join(
        f'<div style="text-align:center">{svg("klucode-favicon.svg", f"{s}px")}'
        f'<div style="font:400 9px/1.3 var(--font-mono);color:var(--kc-textMuted);'
        f'margin-top:8px">{s}px</div></div>'
        for s in (16, 24, 32, 48, 64)
      )
    + '</div>'
    + cap('Favicon — brackets dropped on purpose: below ~32px the 4-unit strokes collapse, only the node-K survives')
  )}
  {panel(svg('klucode-avatar.svg','96px') + cap('Avatar 512² — LinkedIn, GitHub'), dark=True)}
</div>

<div style="margin-top:18px">
  {panel(f'<div style="border-radius:6px;overflow:hidden">{svg("klucode-linkedin-banner.svg","100%")}</div>' + cap('LinkedIn banner 1128×191'))}
</div>
""")

# ---------------------------------------------------------------- sheet 2
SHEETS.append(f"""
{eyebrow('Brand system · 02')}
{h2('Colour')}
{note('Both scales are generated in OKLCH — even lightness ladder, chroma peaking at 500/600 and tapering, deliberate hue torsion. Every ratio below was measured, not estimated. The two numbers under each swatch are contrast on paper #F5F8F6 / on ink #1C201C.')}

<div style="border:2px solid var(--kc-warning);background:var(--kc-warningSurface, #F6EFE2);
            border-radius:10px;padding:20px 24px;margin-bottom:26px">
  <p style="font:700 17px/1.3 var(--font-display);margin:0 0 6px;color:var(--kc-stone-900)">
    Viridian #5EA472 is a display colour, not a text colour</p>
  <p style="font:400 13px/1.6 var(--font-body);margin:0;color:var(--kc-stone-800);max-width:88ch">
    It measures <b>2.79:1</b> on paper — far below the 4.5:1 WCAG AA threshold for normal text.
    Use it for the logo, large display headings, rules, icons and fills. For text and for button
    fills use <b>viridian-700</b> (#396C43), which reads <b>5.78:1</b> both as text on paper
    and as a fill under a paper label.
  </p>
</div>

<p style="font:500 11px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
          color:var(--kc-textMuted);margin:0 0 10px">Viridian — ★ is the brand colour</p>
<div style="display:flex;gap:8px;margin-bottom:26px">{swatches(VIRIDIAN, star='500')}</div>

<p style="font:500 11px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
          color:var(--kc-textMuted);margin:0 0 10px">Stone — near-neutral, chroma 0.004-0.010. 50 is paper, 950 is ink</p>
<div style="display:flex;gap:8px;margin-bottom:26px">{swatches(STONE)}</div>

<div style="display:grid;grid-template-columns:1fr 2fr;gap:18px">
  <div>
    <p style="font:500 11px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
              color:var(--kc-textMuted);margin:0 0 10px">Alternating surface · alert surface</p>
    <div style="display:flex;gap:8px">
      {swatches([('alt','#F0F9F4',1.0,15.37),('warn','#F6EFE2',1.05,14.86)])}
    </div>
  </div>
  <div>
    <p style="font:500 11px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
              color:var(--kc-textMuted);margin:0 0 10px">Proportion — the green lands because it is rationed</p>
    <div style="display:flex;height:74px;border-radius:6px;overflow:hidden;
                border:1px solid rgba(12,26,21,.08)">
      <div style="flex:70;background:var(--kc-stone-50)"></div>
      <div style="flex:20;background:var(--kc-stone-200)"></div>
      <div style="flex:8;background:var(--kc-viridian-500)"></div>
    </div>
    <p style="font:400 10px/1.4 var(--font-mono);color:var(--kc-textMuted);margin-top:7px">
      72% paper or ink · 20% stone · 8% viridian</p>
  </div>
</div>
""")

# ---------------------------------------------------------------- sheet 3
def spec(family, var, weights, desc, sample, size, weight, tracking="0"):
    return panel(f"""
      <div style="display:flex;justify-content:space-between;align-items:baseline;gap:20px">
        <p style="font:700 19px/1.2 var(--font-display);margin:0;color:var(--kc-text)">{family}</p>
        <p style="font:400 10px/1.3 var(--font-mono);color:var(--kc-textMuted);margin:0">
          OFL · {weights}</p>
      </div>
      <p style="font:400 12px/1.55 var(--font-body);color:var(--kc-textMuted);margin:6px 0 16px;
                max-width:72ch">{desc}</p>
      <p style="font:{weight} {size} {var};letter-spacing:{tracking};margin:0;color:var(--kc-text)">
        {sample}</p>
    """)


SHEETS.append(f"""
{eyebrow('Brand system · 03')}
{h2('Typography, texture, spacing')}
{note('Three open-licensed families — self-hosted, which is a legal requirement in Germany, not a preference. Loading them from fonts.googleapis.com transmits visitor IPs to Google.')}

<div style="display:flex;flex-direction:column;gap:14px;margin-bottom:26px">
  {spec('Space Grotesk', 'var(--font-display)', '500 · 700',
        'Display. Headlines, the wordmark, numbers in stat blocks. A geometric grotesque with enough irregularity to be recognisable rather than merely neutral — its K and C echo the mark.',
        'Klug gebaut. Software, mit der Ihr Betrieb arbeitet.', '30px', '700', '-.02em')}
  {spec('Inter', 'var(--font-body)', '400 · 500 · 600',
        'Body. All running text, UI, forms. The most legible German-language UI face available free — which matters when the copy is full of ä, ö, ü, ß and 20-letter compounds.',
        'Die Provisionsabrechnung läuft automatisch — statt jeden Monat drei Tage Excel.', '17px', '400')}
  {spec('JetBrains Mono', 'var(--font-mono)', '400 · 500',
        'Micro-labels, tags, stack lists. The quiet signal that a developer built this page. Never body copy, never more than four words.',
        'REACT · NODE.JS · POSTGRESQL · PLESK', '13px', '500', '.04em')}
</div>

<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px">
  {panel(
    f'<div style="border-radius:6px;overflow:hidden">{svg("klucode-texture-light.svg","100%")}</div>'
    + cap('Node texture, light')
  )}
  {panel(
    f'<div style="border-radius:6px;overflow:hidden">{svg("klucode-texture-dark.svg","100%")}</div>'
    + cap('Node texture, ink — the only decoration the brand owns', True), dark=True
  )}
</div>

<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px">
  {panel(
    '<div style="display:flex;align-items:flex-end;gap:9px;height:80px">'
    + "".join(
        f'<div style="text-align:center"><div style="width:26px;background:var(--kc-viridian-{300 if i<4 else 500});'
        f'height:{min(h,72)}px;border-radius:3px"></div>'
        f'<div style="font:400 9px/1.3 var(--font-mono);color:var(--kc-textMuted);margin-top:6px">{lbl}</div></div>'
        for i,(lbl,h) in enumerate([('1',4),('2',8),('3',12),('4',16),('6',24),('8',32),('12',48),('16',64),('24',72)])
      )
    + '</div>' + cap('Spacing — 4px base grid')
  )}
  {panel(
    '<div style="display:flex;align-items:center;gap:14px;height:80px">'
    + "".join(
        f'<div style="text-align:center"><div style="width:52px;height:52px;background:var(--kc-viridian-100);'
        f'border:1px solid var(--kc-viridian-300);border-radius:{r}"></div>'
        f'<div style="font:400 9px/1.3 var(--font-mono);color:var(--kc-textMuted);margin-top:6px">{lbl}</div></div>'
        for lbl,r in [('sm','4px'),('md','8px'),('lg','14px'),('full','9999px')]
      )
    + '</div>' + cap('Radius — restrained; the logo nodes supply the roundness')
  )}
</div>
""")


# ---------------------------------------------------------------- sheet 4
def glass_demo(dark: bool) -> str:
    scheme = "dark" if dark else "light"
    bg = "var(--kc-stone-900)" if dark else "var(--kc-stone-50)"
    return f"""
    <div data-theme="{scheme}" style="position:relative;isolation:isolate;overflow:hidden;
                border-radius:12px;background:{bg};padding:30px 28px;min-height:250px">
      <div class="aurora grain" style="z-index:-1"></div>
      <p style="font:500 10px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
                color:var(--kc-brandText);margin:0 0 12px">{scheme}</p>
      <div style="display:flex;gap:12px;margin-bottom:14px">
        <div class="glass" style="flex:1;border-radius:1.25rem;padding:16px 18px">
          <p style="font:700 15px/1.2 var(--font-display);margin:0 0 5px;color:var(--kc-text)">glass</p>
          <p style="font:400 12px/1.5 var(--font-body);color:var(--kc-textMuted);margin:0">
            Clear pane, refracting edge, one sheen.</p>
        </div>
        <div class="glass-solid" style="flex:1;border-radius:1.25rem;padding:16px 18px">
          <p style="font:700 15px/1.2 var(--font-display);margin:0 0 5px;color:var(--kc-text)">glass-solid</p>
          <p style="font:400 12px/1.5 var(--font-body);color:var(--kc-textMuted);margin:0">
            Long copy and form fields.</p>
        </div>
      </div>
      <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap">
        <span style="background:var(--kc-brandAction);color:var(--kc-onBrand);border-radius:9999px;
                     padding:9px 18px;font:500 13px/1 var(--font-display);
                     box-shadow:0 6px 20px -6px rgba(53,108,91,.55)">Projekt besprechen</span>
        <span class="glass" style="border-radius:9999px;padding:9px 18px;
                     font:500 13px/1 var(--font-display);color:var(--kc-text)">Projekte ansehen</span>
        <span class="glass" style="border-radius:9999px;padding:6px 13px;
                     font:400 10px/1.3 var(--font-mono);color:var(--kc-textMuted)">POSTGRESQL</span>
      </div>
    </div>"""


SHEETS.append(f"""
{eyebrow('Brand system · 04')}
{h2('Clear glass')}
{note('Panes you look THROUGH, floating over an aurora wash — not frosted rectangles you look at. No panel has a border: the edge is optical, an SVG displacement map that bends the backdrop within 14px of the boundary, plus one asymmetric sheen. A painted stroke around a translucent box reads as a border no matter how it is tuned. The fill is LOW (0.10 light, 0.16 dark) at 6px blur, because clear glass transmits; at 0.44 and 12px the panels were milky. The guardrail is not a fixed opacity, it is the audit: composited contrast is sampled from rendered pixels.')}

<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:26px">
  {glass_demo(False)}
  {glass_demo(True)}
</div>

<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px">
  {panel('<p style="font:700 15px/1.25 var(--font-display);margin:0 0 6px;color:var(--kc-text)">1 · Fills transmit colour</p>'
         '<p style="font:400 12px/1.55 var(--font-body);color:var(--kc-textMuted);margin:0">'
         '0.10 light, 0.16 dark — low enough to transmit the aurora. The number is not sacred; '
         'the measured audit is. Change a fill, re-run it.</p>')}
  {panel('<p style="font:700 15px/1.25 var(--font-display);margin:0 0 6px;color:var(--kc-text)">2 · Copy sits on solid</p>'
         '<p style="font:400 12px/1.55 var(--font-body);color:var(--kc-textMuted);margin:0">'
         'Long text and form fields use glass-solid — 92% opaque. Keeps the blur, takes no chances.</p>')}
  {panel('<p style="font:700 15px/1.25 var(--font-display);margin:0 0 6px;color:var(--kc-text)">3 · Primary is never glass</p>'
         '<p style="font:400 12px/1.55 var(--font-body);color:var(--kc-textMuted);margin:0">'
         'Solid viridian-600. The one element whose contrast may not depend on what is behind it.</p>')}
  {panel('<p style="font:700 15px/1.25 var(--font-display);margin:0 0 6px;color:var(--kc-text)">4 · No panel gets a border</p>'
         '<p style="font:400 12px/1.55 var(--font-body);color:var(--kc-textMuted);margin:0">'
         'If one stops reading as glass, the aurora behind it is too weak. Fix the ground, not the edge.</p>')}
</div>

<div style="margin-top:20px;border:1px solid var(--kc-border);border-radius:10px;padding:18px 22px">
  <p style="font:500 10px/1.2 var(--font-mono);letter-spacing:.08em;text-transform:uppercase;
            color:var(--kc-brandText);margin:0 0 8px">Measured on composited pixels, both schemes</p>
  <p style="font:400 12px/1.6 var(--font-body);color:var(--kc-textMuted);margin:0;max-width:96ch">
    Declared CSS colours lie once translucency is involved. Every text role was sampled from the
    rendered page and checked against its WCAG threshold in BOTH themes: all pass, the tightest at
    5.74:1 against a 4.5 requirement. Re-run the audit after any change to fill opacity or aurora
    strength. Note the panels above render without the runtime lens, so they show the clear pane
    without its bending — that is exactly the Firefox fallback.</p>
</div>
""")

sheets_html = "".join(
    f'<section class="sheet" id="sheet{i+1}" style="width:1500px;box-sizing:border-box;'
    f'padding:54px 58px;background:var(--kc-surface)">{s}'
    f'<p style="font:400 10px/1.3 var(--font-mono);color:var(--kc-textMuted);'
    f'margin:34px 0 0;padding-top:16px;border-top:1px solid var(--kc-border);'
    f'text-transform:uppercase;letter-spacing:.06em">'
    f'KluCode brand system — sheet {i+1} of {len(SHEETS)}</p></section>'
    for i, s in enumerate(SHEETS)
)

(OUT / "board.html").write_text(f"""<!doctype html>
<html lang="de" class="{cls}">
<head><meta charset="utf-8"><link rel="stylesheet" href="{css}"><title>KluCode brand system</title>
<style>body{{margin:0;background:#d8dcd7}} .sheet + .sheet{{margin-top:22px}} svg{{display:block}}</style>
</head><body>{sheets_html}</body></html>""")
print("wrote", OUT / "board.html", f"({len(SHEETS)} sheets)")
